models/Bet.php
<?php

namespace app\models;

use Yii;
use amnah\yii2\user\models\User;

/**
 * This is the model class for table "bet".
 *
 * @property string $id
 * @property string $user_id
 * @property string $match_id
 * @property integer $option
 * @property integer $is_active
 * @property integer $money
 * @property string $created_time
 *
 * @property User $user
 * @property Match $match
 */
class Bet extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bet';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $max_money_value = Yii::$app->user->money;
        $action = strtolower(Yii::$app->controller->action->id);
        if ($action == "update") {
            $id = (int)Yii::$app->request->get('id');
            $max_money_value += Bet::findOne($id)->money;
        }
        return [
            [['user_id', 'match_id', 'option', 'money'], 'integer'],
            [['option', 'money'], 'required'],
            [['money'],'integer', 'min' => 1],
            //[['money'], 'isDivisibleByTen'],
            [['money'], 'compare',
                'operator' => '<=',
                'compareValue' => $max_money_value,
                //'message' => 'Please check your available money.'
            ],
            [['option'], 'in', 'range' => [0, 1, 2]],
            [['user_id', 'match_id'], 'unique',
                'targetAttribute' => ['user_id', 'match_id'],
                'message' => 'You have already betted this match.'],
            [['created_time'], 'safe']
        ];
    }

    public function isDivisibleByTen($attribute) {
        if (($this->$attribute % 10) != 0) {
            $this->addError($attribute, 'must be multiple of 10');
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'match_id' => 'Match ID',
            'option' => 'Option',
            'money' => 'Money',
            'created_time' => 'Created Time',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMatch()
    {
        return $this->hasOne(Match::className(), ['id' => 'match_id']);
    }

    /**
     * Check if the bet is exist
     * @param $user_id
     * @param $match_id
     * @return bool|\app\models\Bet
     */
    public static function isExist($user_id, $match_id)
    {
        $model = self::findOne(['user_id' => $user_id, 'match_id' => $match_id]);
        if ($model !== null)
            return $model;
        return false;
    }

    public function getBettingOption()
    {
        switch ($this->option) {
            case 1:
                return $this->match->team_1;
            case 2:
                return $this->match->team_2;
            default:
                return "-";
        }
    }

    public function getBettedResult()
    {
        if (is_null($this->match->result)) {
            return "-";
        }
        elseif ($this->match->result == 0)
            return "Draw";
        elseif ($this->match->result == $this->option)
            return "Win";
        else
            return "Lose";
    }

    /**
     * Cong/tru tien cua moi user sau khi co ket qua tran dau
     * @param $bet_result
     */
    public function updateBetMoneyResult($bet_result)
    {
        if ($this->is_active) {
            if ($bet_result != 0) {
                if ($this->option == $bet_result) {
                    $this->user->updateMoney( 2*$this->money );
                }
            } else {
                // ket qua hoa, tra tien lai user
                $this->user->updateMoney( $this->money );
            }
            // khoa' bet hien tai
            $this->is_active = false;
            $this->save(false, ['is_active']);
        }
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->is_active = true;
        } else {
            $this->created_time = date('Y-m-d H:i:s');
        }
        return parent::beforeSave($insert);
    }

    /**
     * Cong/tru tien cua user sau moi lan bet
     * @param bool $insert
     */
    public function afterSave($insert)
    {
        // tru tien da dat cuoc
        if ($this->is_active) {
            if ($insert) {
                $value = ( 0 - $this->money );
            } else {
                $value = $this->oldAttributes['money'] - $this->money;
            }
            $this->user->updateMoney($value);
        }
        return parent::afterSave($insert);
    }

    /**
     * Cong/tru tien cua user sau khi huy lan bet
     */
    public function afterDelete()
    {
        $this->user->updateMoney($this->money);
        return parent::afterDelete();
    }
}

controllers/BetController.php
<?php

namespace app\controllers;

use amnah\yii2\user\models\User;
use Yii;
use app\models\Bet;
use app\models\Match;
use app\models\BetSearch;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * BetController implements the CRUD actions for Bet model.
 */
class BetController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
//                        'actions' => Yii::$app->user->can("admin") ?
//                                ['view', 'create', 'update', 'delete'] :
//                                ['view', 'create', 'update'],
                        'actions' => ['view', 'view-by-user', 'create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
//    public function init() {
//
//        // check for admin permission in web requests. console requests should not throw the exception
//        if (!isset($_GET['match_id']) || (int)$_GET['match_id'] == 0) {
//            throw new NotFoundHttpException('The requested page does not exist.');
//        }
//
//        parent::init();
//    }

    /**
     * Lists all Bet models.
     * @return mixed
     */
//    public function actionIndex()
//    {
//        $searchModel = new BetSearch;
//        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
//
//        return $this->render('index', [
//            'dataProvider' => $dataProvider,
//            'searchModel' => $searchModel,
//        ]);
//    }

    /**
     * View all bets of a match
     * @return string
     */

    public function actionView()
    {
        $match_id = (int)$_GET['match_id'];
        $searchModel = new BetSearch;
        $searchModel->match_id = $match_id;
        if (!isset($_GET['sort'])) $_GET['sort'] = '-created_time';
        $dataProvider = $searchModel->search(['BetSearch' => $searchModel->attributes]);

        return $this->render('view', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'match' => $this->findMatchModel($match_id),
        ]);
    }

    /**
     * View bet history of a user
     * @param $id
     * @return string
     */
    public function actionViewByUser($id)
    {
        $searchModel = new BetSearch;
        $searchModel->user_id = $id;
        if (!isset($_GET['sort'])) $_GET['sort'] = '-created_time';
        $dataProvider = $searchModel->search(['BetSearch' => $searchModel->attributes]);

        return $this->render('view-user-history', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'user' => $this->findUserModel($id),
        ]);
    }

    /**
     * @return string|\yii\web\Response
     * @throws \yii\web\BadRequestHttpException
     */
    public function actionCreate()
    {
        $model = new Bet;
        $match = $this->findMatchModel((int)$_GET['match_id']);

        if (!$match->canBet())
            throw new NotFoundHttpException('The requested page does not exist.');
        else if (Yii::$app->user->money <= 0) {
            throw new BadRequestHttpException('Sorry, you don\'t have enough money to create new bet.');
        } elseif (Bet::isExist(Yii::$app->user->id, $match->id)) {
            throw new BadRequestHttpException('You have already betted this match.');
        }

        if ($model->load(Yii::$app->request->post())) {
            $model->user_id = Yii::$app->user->id;
            $model->match_id = $match->id;
            if ($model->save())
                //return $this->redirect(['view', 'id' => $model->id]);
                return $this->redirect(['/match']);
        } else {
            return $this->render('create', [
                'model' => $model,
                'match' => $match
            ]);
        }
    }

    /**
     * Update an existing bet model
     * @param $id
     * @return string|\yii\web\Response
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->user_id != Yii::$app->user->id || !$model->match->canBet())
            throw new NotFoundHttpException('The requested page does not exist.');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            //return $this->redirect(['view', 'id' => $model->id]);
            return $this->redirect(['/match']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Bet model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if ($model->user_id != Yii::$app->user->id || !$model->match->canBet())
            throw new NotFoundHttpException('The requested page does not exist.');

        $model->delete();

        return $this->redirect(['/match/index']);
    }

    /**
     * Finds the Bet model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Bet the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Bet::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function findMatchModel($id)
    {
        if (($model = Match::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Sorry, the match does not exist.');
        }
    }

    protected function findUserModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Sorry, the user does not exist.');
        }
    }
}

controllers/MatchController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Match;
use app\models\MatchSearch;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * MatchController implements the CRUD actions for Match model.
 */
class MatchController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => Yii::$app->user->can("admin") ?
                                ['index', 'view', 'create', 'update', 'update-score', 'delete'] :
                                ['index', 'view'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }


    /**
     * Lists all Match models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MatchSearch;
        if (!isset($_GET['sort'])) $_GET['sort'] = '-match_date';
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single Match model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Match model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Match;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
//            return $this->redirect(['view', 'id' => $model->id]);
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model
            ]);
        }
    }

    /**
     * Updates an existing Match model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if (!$model->canUpdate())
            throw new BadRequestHttpException('Sorry, you can not update this match anymore.');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
//            return $this->redirect(['view', 'id' => $model->id]);
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdateScore($id)
    {
        $model = $this->findModel($id);

        if (isset($model->result))
            throw new BadRequestHttpException('Sorry, you can not update this match anymore.');

        $request = Yii::$app->request;
        $post = $request->post();
        if ($request->isPost && isset($post['auto_result']) && $post['auto_result'] == '1') {
            $post['Match']['result'] = null;

        }

        if ($model->load($post) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
                'update_score' => true
            ]);
        }
    }

    /**
     * Deletes an existing Match model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {

        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Match model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Match the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Match::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/bet/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\Bet $model
 * @var app\models\Match $match
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="bet-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'option')->dropDownList([
        '' => '',
        1 => $match->team_1,
        2 => $match->team_2,
    ]) ?>

    <?= $form->field($model, 'money')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/bet/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\BetSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="bet-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'match_id') ?>

    <?= $form->field($model, 'option') ?>

    <?= $form->field($model, 'money') ?>

    <?php // echo $form->field($model, 'created_time') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/bet/create.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\Bet $model
 * @var app\models\Match $match
 */
$this->title = "Create Bet: " . $match->getMatchName();
$this->params['breadcrumbs'][] = ['label' => $match->getMatchName(), 'url' => ['/match/view', 'id' => $match->id]];
$this->params['breadcrumbs'][] = 'Create Bet';
?>
<div class="bet-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'match' => $match
    ]) ?>

</div>

views/bet/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\BetSearch $searchModel
 */

$this->title = 'Bets';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bet-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Bet', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'user_id',
            'match_id',
            'option',
            'money',
            // 'created_time',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

views/bet/update.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\Bet $model
 */

$this->title = 'Update Bet: ' . $model->match->getMatchName();
$this->params['breadcrumbs'][] = ['label' => $model->match->getMatchName(), 'url' => ['/match/view', 'id' => $model->match_id]];
$this->params['breadcrumbs'][] = 'Update Bet';
?>
<div class="bet-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'match' => $model->match
    ]) ?>

</div>

views/bet/view-user-history.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\assets\Helper;

/**
 * @var yii\web\View $this
 * @var app\models\Bet $model
 * @var amnah\yii2\user\models\User $user
 */

$this->title = "View All Bets";
$this->params['breadcrumbs'][] = ['label' => 'Ranking', 'url' => ['/user/default/ranking']];
$this->params['breadcrumbs'][] = $user->email;
?>
<div class="bet-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'match_id',
                'label' => 'Match Name',
                'value' => function($model, $index, $dataColumn) {
                        return $model->match->getMatchName();
                    }
            ],
            [
                'label' => 'Match Date',
                'value' => function($model, $index, $dataColumn) {
                        return Helper::printDatetime($model->match->match_date, "%b %d, %Y %I:%M %p");
                    }
            ],
            [
                'attribute' => 'option',
                'value' => function($model, $index, $dataColumn) {
                        return $model->getBettingOption();
                    }
            ],
            'money',
            [
                'attribute' => 'created_time',
                'label' => 'Bet Time',
                'headerOptions' => [
                    'width' => '170',
                ],
                'value' => function($model, $index, $dataColumn) {
                        return Helper::printDatetime($model->created_time, "%b %d, %Y %I:%M %p");
                    }
            ],
            [
                'label' => 'Result',
                'value' => function($model, $index, $dataColumn) {
                        return $model->getBettedResult();
                    },
            ],
            /*[
                'class' => 'yii\grid\ActionColumn',
                'template' => '{delete}',
                'headerOptions' => [
                    'width' => '25'
                ],
                'visible' => Yii::$app->user->can('admin')
            ],*/
        ],
    ]); ?>

</div>

views/bet/view.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\assets\Helper;

/**
 * @var yii\web\View $this
 * @var app\models\Bet $model
 * @var app\models\Match $match
 */

$this->title = $match->getMatchName() . " / " . "View All Bets";
$this->params['breadcrumbs'][] = ['label' => 'Matches', 'url' => ['/match/index']];
$this->params['breadcrumbs'][] = ['label' => $match->getMatchName(), 'url' => ['/match/view', 'id' => $match->id]];
$this->params['breadcrumbs'][] = "View All Bets";
?>
<div class="bet-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'user_id',
                'label' => 'Username',
                'value' => function($model, $index, $dataColumn) {
                        return $model->user->username;
                    }
            ],
            [
                'label' => 'Email',
                'value' => function($model, $index, $dataColumn) {
                        return $model->user->email;
                    }
            ],
            [
                'attribute' => 'option',
                'value' => function($model, $index, $dataColumn) {
                        return $model->getBettingOption();
                    }
            ],
            'money',
            [
                'attribute' => 'created_time',
                'label' => 'Bet Time',
                'headerOptions' => [
                    'width' => '170',
                ],
                'value' => function($model, $index, $dataColumn) {
                        return Helper::printDatetime($model->created_time, "%b %d, %Y %I:%M %p");
                    }
            ],
            [
                'label' => 'Result',
                'value' => function($model, $index, $dataColumn) {
                        return $model->getBettedResult();
                    },
                'visible' => !is_null($match->result)
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{delete}',
                'headerOptions' => [
                    'width' => '25'
                ],
                'visible' => Yii::$app->user->can('admin')
            ],
        ],
    ]); ?>

</div>