models/Match.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "match".
 *
 * @property string $id
 * @property string $campaign_id
 * @property string $team_1
 * @property string $team_2
 * @property integer $team_1_score
 * @property integer $team_2_score
 * @property double $rate
 * @property integer $result
 * @property string $match_date
 * @property string $description
 * @property string $created_by
 * @property string $created_time
 * @property string $modified_time
 *
 * @property Bet[] $bets
 * @property Campaign $campaign
 * @property User $createdBy
 */
class Match extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'match';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $action = strtolower(Yii::$app->controller->action->id);
        return [
            [['campaign_id', 'team_1_score', 'team_2_score', 'result', 'created_by'], 'integer'],
            [['rate'], 'number'],
            [['rate'], 'isDivisibleByHalf'],
//            [['match_date'], 'compare',
//                'operator' => '>',
//                'compareValue' => date('Y-m-d H:i:s')
//            ],
            [['match_date', 'created_time', 'modified_time'], 'safe'],
            [['description'], 'string'],
            [['team_1', 'team_2'], 'string', 'max' => 50],
            [['team_1_score', 'team_2_score'], 'integer', 'min' => 0],
            ($action != 'update-score') ?
                [['team_1', 'team_2', 'match_date', 'rate'], 'required'] :
                [['team_1_score', 'team_2_score'], 'required']
        ];
    }

    public function isDivisibleByHalf($attribute) {
        $round = round($this->$attribute, 1) * 10;
        if ($round % 5 != 0) {
            $this->addError($attribute, 'Rate must be multiple of 0.5');
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'campaign_id' => 'Campaign ID',
            'team_1' => 'Team 1',
            'team_2' => 'Team 2',
            'team_1_score' => 'Team 1 Score',
            'team_2_score' => 'Team 2 Score',
            'rate' => 'Rate',
            'result' => 'Result',
            'match_date' => 'Match Date',
            'description' => 'Description',
            'created_by' => 'Created By',
            'created_time' => 'Created Time',
            'modified_time' => 'Modified Time',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBets()
    {
        return $this->hasMany(Bet::className(), ['match_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCampaign()
    {
        return $this->hasOne(Campaign::className(), ['id' => 'campaign_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * @return string
     */
    public  function getMatchName()
    {
        return $this->team_1 .' - '. $this->team_2;
    }

    public function getRateText()
    {
        if ($this->rate == 0) {
            return "0:0";
        }if ($this->rate > 0) {
            return "0:" . $this->rateToString($this->rate);
        } else {
            return $this->rateToString($this->rate) . ":0";
        }
    }

    protected function rateToString($rate) {
        $rate = abs($rate);
        $round = round($rate, 0, PHP_ROUND_HALF_DOWN);
        if ($round == $rate) {
            return $rate;
        } else {
            return ($round > 0 ? $round." " : "") . "1/2";
        }
    }

    /**
     * Chi cho bet truoc tran dau dien ra 5 phut.
     * Vd tran dau dien ra luc 10h thi 9h55 ko cho bet.
     * @return bool
     */
    public function canBet()
    {
        return $this->canUpdate() && (is_null($this->match_date) || date('Y-m-d H:i:s', strtotime('+5 minutes')) <= $this->match_date);
    }

    /**
     * @return bool
     */
    public function canUpdate()
    {
       return (is_null($this->result));
    }

    public function canDelete()
    {
        return (count($this->bets) <= 0);

    }

    public function beforeSave($insert)
    {
        if (!is_null($this->rate) && is_null($this->result)) // update tran dau chua dien ra
        {
            $this->rate = round($this->rate, 1);
        }
        // update ti so => ket qua ca cuoc cua tran dau
        if (!is_null($this->team_1_score) && !is_null($this->team_2_score) && is_null($this->result))
        {
            $rate = $this->team_1_score - $this->team_2_score;
            $this->result = 0;
            if ($rate > $this->rate) {
                $this->result = 1;
            } else if ($rate < $this->rate) {
                $this->result = 2;
            }
        }

        return parent::beforeSave($insert);
    }

    public function afterSave($insert)
    {
        // sau khi co ket qua tran dau
        // 1. quet tat ca cac user da tham gia dat cuoc
        // 2. xet ket qua dat cuoc de cong, tru tien cho moi user
        if (!is_null($this->result))
        {
            foreach ($this->bets as $bet)
                $bet->updateBetMoneyResult($this->result);
        }

        return parent::afterSave($insert);
    }
}

controllers/BetController.php
<?php

namespace app\controllers;

use amnah\yii2\user\models\User;
use Yii;
use app\models\Bet;
use app\models\Match;
use app\models\BetSearch;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * BetController implements the CRUD actions for Bet model.
 */
class BetController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
//                        'actions' => Yii::$app->user->can("admin") ?
//                                ['view', 'create', 'update', 'delete'] :
//                                ['view', 'create', 'update'],
                        'actions' => ['view', 'view-by-user', 'create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
//    public function init() {
//
//        // check for admin permission in web requests. console requests should not throw the exception
//        if (!isset($_GET['match_id']) || (int)$_GET['match_id'] == 0) {
//            throw new NotFoundHttpException('The requested page does not exist.');
//        }
//
//        parent::init();
//    }

    /**
     * Lists all Bet models.
     * @return mixed
     */
//    public function actionIndex()
//    {
//        $searchModel = new BetSearch;
//        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
//
//        return $this->render('index', [
//            'dataProvider' => $dataProvider,
//            'searchModel' => $searchModel,
//        ]);
//    }

    /**
     * View all bets of a match
     * @return string
     */

    public function actionView()
    {
        $match_id = (int)$_GET['match_id'];
        $searchModel = new BetSearch;
        $searchModel->match_id = $match_id;
        if (!isset($_GET['sort'])) $_GET['sort'] = '-created_time';
        $dataProvider = $searchModel->search(['BetSearch' => $searchModel->attributes]);

        return $this->render('view', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'match' => $this->findMatchModel($match_id),
        ]);
    }

    /**
     * View bet history of a user
     * @param $id
     * @return string
     */
    public function actionViewByUser($id)
    {
        $searchModel = new BetSearch;
        $searchModel->user_id = $id;
        if (!isset($_GET['sort'])) $_GET['sort'] = '-created_time';
        $dataProvider = $searchModel->search(['BetSearch' => $searchModel->attributes]);

        return $this->render('view-user-history', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'user' => $this->findUserModel($id),
        ]);
    }

    /**
     * @return string|\yii\web\Response
     * @throws \yii\web\BadRequestHttpException
     */
    public function actionCreate()
    {
        $model = new Bet;
        $match = $this->findMatchModel((int)$_GET['match_id']);

        if (!$match->canBet())
            throw new NotFoundHttpException('The requested page does not exist.');
        else if (Yii::$app->user->money <= 0) {
            throw new BadRequestHttpException('Sorry, you don\'t have enough money to create new bet.');
        } elseif (Bet::isExist(Yii::$app->user->id, $match->id)) {
            throw new BadRequestHttpException('You have already betted this match.');
        }

        if ($model->load(Yii::$app->request->post())) {
            $model->user_id = Yii::$app->user->id;
            $model->match_id = $match->id;
            if ($model->save())
                //return $this->redirect(['view', 'id' => $model->id]);
                return $this->redirect(['/match']);
        } else {
            return $this->render('create', [
                'model' => $model,
                'match' => $match
            ]);
        }
    }

    /**
     * Update an existing bet model
     * @param $id
     * @return string|\yii\web\Response
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->user_id != Yii::$app->user->id || !$model->match->canBet())
            throw new NotFoundHttpException('The requested page does not exist.');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            //return $this->redirect(['view', 'id' => $model->id]);
            return $this->redirect(['/match']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Bet model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if ($model->user_id != Yii::$app->user->id || !$model->match->canBet())
            throw new NotFoundHttpException('The requested page does not exist.');

        $model->delete();

        return $this->redirect(['/match/index']);
    }

    /**
     * Finds the Bet model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Bet the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Bet::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function findMatchModel($id)
    {
        if (($model = Match::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Sorry, the match does not exist.');
        }
    }

    protected function findUserModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Sorry, the user does not exist.');
        }
    }
}

controllers/MatchController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Match;
use app\models\MatchSearch;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * MatchController implements the CRUD actions for Match model.
 */
class MatchController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => Yii::$app->user->can("admin") ?
                                ['index', 'view', 'create', 'update', 'update-score', 'delete'] :
                                ['index', 'view'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }


    /**
     * Lists all Match models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MatchSearch;
        if (!isset($_GET['sort'])) $_GET['sort'] = '-match_date';
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single Match model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Match model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Match;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
//            return $this->redirect(['view', 'id' => $model->id]);
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model
            ]);
        }
    }

    /**
     * Updates an existing Match model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if (!$model->canUpdate())
            throw new BadRequestHttpException('Sorry, you can not update this match anymore.');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
//            return $this->redirect(['view', 'id' => $model->id]);
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdateScore($id)
    {
        $model = $this->findModel($id);

        if (isset($model->result))
            throw new BadRequestHttpException('Sorry, you can not update this match anymore.');

        $request = Yii::$app->request;
        $post = $request->post();
        if ($request->isPost && isset($post['auto_result']) && $post['auto_result'] == '1') {
            $post['Match']['result'] = null;

        }

        if ($model->load($post) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
                'update_score' => true
            ]);
        }
    }

    /**
     * Deletes an existing Match model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {

        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Match model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Match the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Match::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/match/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\datetimepicker\DateTimePicker;


/**
 * @var yii\web\View $this
 * @var app\models\Match $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="match-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'team_1')->textInput(['maxlength' => 50]) ?>

    <?= $form->field($model, 'team_2')->textInput(['maxlength' => 50]) ?>

    <?= $form->field($model, 'match_date')->widget(DateTimePicker::className(), [
        //'pickButtonIcon' => 'glyphicon glyphicon-time',
        //'inline' => true,
        'clientOptions' => [
            'startView' => 1,
            'autoclose' => true,
            //'linkFormat' => 'HH:ii P', // if inline = true
            'format' => 'yyyy-mm-dd hh:ii:ss', // if inline = false
            'showMeridian' => true,
            'pickerPosition' => "bottom-left",
            'minuteStep' => 15,
            'startDate' => date('Y-m-d H:i:s'),
            'todayBtn' => true,
        ]
    ]);?>

    <?= $form->field($model, 'rate')->textInput(['maxlength' => 50]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/match/_form_score.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;


/**
 * @var yii\web\View $this
 * @var app\models\Match $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="match-form">

    <?php $form = ActiveForm::begin([
        'beforeSubmit' => new \yii\web\JsExpression('function($form) {
            if (confirm("Are you sure ?")) {
                $form.find(":submit").attr("disabled", true);
                return true;
            }
            return false;
        }'),
    ]); ?>

    <div class="alert alert-warning">
        <p><b>Note:</b> After you update score of this match, you cannot update this match anymore.</p>
    </div>

    <?= $form->field($model, 'team_1_score')->textInput()->label($model->team_1) ?>

    <?= $form->field($model, 'team_2_score')->textInput()->label($model->team_2) ?>

    <div class="form-group">
        <label style="font-weight: normal">
            <input id="auto-result" name="auto_result" type="checkbox" value="1" checked="checked" />
        Auto generate the bet result of this match.</label>
    </div>

    <div id="hidden-wrapper" style="display: none">
        <?= $form->field($model, 'result', [
                /*'options'=> [
                    'id' => 'result-wrapper',
                    'style' => 'display: none'
                ]*/
            ])->dropDownList([
                0 => 'Draw',
                1 => $model->team_1,
                2 => $model->team_2,
            ])->label('Bet result'); ?>

        <?= $form->field($model, 'description')->textarea(['rows' => 6]); ?>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Update Score',[
                'class' => 'btn btn-primary'
        ]) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php $this->registerJs("
    var \$divResult = $('#hidden-wrapper');
    $('#auto-result').change(function(){
        if ($(this).is(':checked')) {
            \$divResult.css('display', 'none');
            $(this).val(1);
        } else {
            \$divResult.css('display', 'block');
            $(this).val(0);
        }
    });

", \yii\web\View::POS_END); ?>

views/match/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\MatchSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="match-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'team_1') ?>

    <?= $form->field($model, 'team_2') ?>

    <?= $form->field($model, 'team_1_score') ?>

    <?= $form->field($model, 'team_2_score') ?>

    <?php // echo $form->field($model, 'result') ?>

    <?php // echo $form->field($model, 'match_date') ?>

    <?php // echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'created_time') ?>

    <?php // echo $form->field($model, 'modified_time') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/match/create.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\Match $model
 */

$this->title = 'Create Match';
$this->params['breadcrumbs'][] = ['label' => 'Matches', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="match-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/match/index.php
<?php

use app\assets\Helper;
use yii\helpers\Html;
use yii\grid\GridView;
use \app\models\Bet;
/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\MatchSearch $searchModel
 */

$this->title = 'Matches';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="match-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <?php if (Yii::$app->user->can('admin')) : ?>
    <p>
        <?= Html::a('Create Match', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?php endif; ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'team_1',
            [
                'attribute' => 'team_2_score',
                'filter' => false,
                'label' => '',
                'headerOptions' => [
                    'width' => '40'
                ],
                'value' => function($model, $index, $dataColumn) {
                        return is_null($model->team_1_score) ? "?" : $model->team_1_score;
                    }
            ],
            [
                'attribute' => 'team_2_score',
                'filter' => false,
                'label' => '',
                'headerOptions' => [
                    'width' => '40'
                ],
                'value' => function($model, $index, $dataColumn) {
                        return is_null($model->team_2_score) ? "?" : $model->team_2_score;
                    }
            ],
            'team_2',
            [
                'attribute' => 'match_date',
                'headerOptions' => [
                    'width' => '170'
                ],
                'value' => function($model, $index, $dataColumn) {
                        return Helper::printDatetime($model->match_date, "%b %d, %Y %I:%M %p");
                    }
            ],
            [
                'attribute' => 'rate',
                'headerOptions' => [
                    'width' => '70'
                ],
                'value' => function($model, $index, $dataColumn) {
                    return $model->getRateText();
                }
            ],
            'description:ntext',
            [
                'label' => 'Your Bet',
                'format' => 'raw',
                'value' => function($model, $index, $dataColumn) {
                        $bet = Bet::isExist(Yii::$app->user->id, $model->id);
                        if ($bet)
                            return $bet->getBettingOption() .' ($'. $bet->money . ') ' .
                            ( $model->canBet() ?
                                Html::a("<span class='glyphicon glyphicon-pencil'></span>", ['bet/update', 'id' => $bet->id]) .
                                Html::a("<span class='glyphicon glyphicon-trash'></span>", ['bet/delete', 'id' => $bet->id], ['data' => ['confirm' => 'Are you sure you want to delete this bet?', 'method'=>'post']])
                                : '' );
                        elseif ($model->canBet())
                            return Html::a("Bet", ['bet/create', 'match_id' => $model->id]);
                        else
                            return '-';
                    }
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => Yii::$app->user->can('admin') ? '{history} {update} {delete}' : '{history}',
                'buttons' => [
                    'history' => function ($url, $model) {
                            return Html::a('<span class="glyphicon glyphicon-list"></span>', array('/bet/view', 'match_id' => $model->id), [
                                'title' => Yii::t('app', 'View All Bets'),
                            ]);
                        },
                    'update' => function ($url, $model) {
                            if ($model->canUpdate())
                                return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                                    'title' => Yii::t('app', 'Update'),
                                ]) . ' ' . Html::a('<span class="glyphicon glyphicon-ok"></span>', ['update-score', 'id' => $model->id], [
                                    'title' => Yii::t('app', 'Update Score'),
                                ]);
                            else
                                return Html::a('<span class="glyphicon glyphicon-info-sign"></span>', array('view', 'id' => $model->id), [
                                    'title' => Yii::t('app', 'View'),
                                ]);
                        },
                    'delete' => function ($url, $model) {
                            if ($model->canDelete())
                                return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                                    'title' => Yii::t('app', 'Delete'),
                                    'data' => [
                                        'confirm' => 'Are you sure you want to delete this match ?',
                                        'method' => 'post'
                                    ]
                                ]);
                            return '';
                        }
                ],

                'headerOptions' => [
                    'width' => Yii::$app->user->can('admin') ? '100' : '25'
                ],
                //'visible' => Yii::$app->user->can('admin')
            ],
        ],
    ]); ?>
</div>

views/match/update.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\Match $model
 */
$this->title = !isset($update_score) ? 'Update Match: ' . $model->getMatchName() : 'Update Score';
$this->params['breadcrumbs'][] = ['label' => 'Matches', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->getMatchName(), 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="match-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render(!isset($update_score) ? '_form' : '_form_score', [
        'model' => $model,
    ]) ?>

</div>

views/match/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/**
 * @var yii\web\View $this
 * @var app\models\Match $model
 */
$this->title = $model->getMatchName();
$this->params['breadcrumbs'][] = ['label' => 'Matches', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="match-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->user->can('admin') && $model->canDelete()): ?>
    <p>
        <?= $model->canUpdate() ? Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) : '' ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <?php endif; ?>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'team_1',
            'team_2',
            'team_1_score',
            'team_2_score',
            'rate',
            'result',
            'match_date',
            'description:ntext',
            //'created_by',
            'created_time',
            'modified_time',
        ],
    ]) ?>

</div>